// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.axxes;

import be.axxes.BlogPostIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BlogPostIntegrationTest_Roo_Configurable {
    
    declare @type: BlogPostIntegrationTest: @Configurable;
    
}
