// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.axxes;

import be.axxes.BlogPost;
import be.axxes.BlogPostDataOnDemand;
import be.axxes.BlogPostIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BlogPostIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BlogPostIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BlogPostIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BlogPostIntegrationTest: @Transactional;
    
    @Autowired
    BlogPostDataOnDemand BlogPostIntegrationTest.dod;
    
    @Test
    public void BlogPostIntegrationTest.testCountBlogPosts() {
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to initialize correctly", dod.getRandomBlogPost());
        long count = BlogPost.countBlogPosts();
        Assert.assertTrue("Counter for 'BlogPost' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BlogPostIntegrationTest.testFindBlogPost() {
        BlogPost obj = dod.getRandomBlogPost();
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to provide an identifier", id);
        obj = BlogPost.findBlogPost(id);
        Assert.assertNotNull("Find method for 'BlogPost' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BlogPost' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BlogPostIntegrationTest.testFindAllBlogPosts() {
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to initialize correctly", dod.getRandomBlogPost());
        long count = BlogPost.countBlogPosts();
        Assert.assertTrue("Too expensive to perform a find all test for 'BlogPost', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BlogPost> result = BlogPost.findAllBlogPosts();
        Assert.assertNotNull("Find all method for 'BlogPost' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BlogPost' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BlogPostIntegrationTest.testFindBlogPostEntries() {
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to initialize correctly", dod.getRandomBlogPost());
        long count = BlogPost.countBlogPosts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BlogPost> result = BlogPost.findBlogPostEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BlogPost' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BlogPost' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BlogPostIntegrationTest.testFlush() {
        BlogPost obj = dod.getRandomBlogPost();
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to provide an identifier", id);
        obj = BlogPost.findBlogPost(id);
        Assert.assertNotNull("Find method for 'BlogPost' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBlogPost(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BlogPost' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BlogPostIntegrationTest.testMergeUpdate() {
        BlogPost obj = dod.getRandomBlogPost();
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to provide an identifier", id);
        obj = BlogPost.findBlogPost(id);
        boolean modified =  dod.modifyBlogPost(obj);
        Integer currentVersion = obj.getVersion();
        BlogPost merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BlogPost' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BlogPostIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to initialize correctly", dod.getRandomBlogPost());
        BlogPost obj = dod.getNewTransientBlogPost(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BlogPost' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BlogPost' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BlogPostIntegrationTest.testRemove() {
        BlogPost obj = dod.getRandomBlogPost();
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BlogPost' failed to provide an identifier", id);
        obj = BlogPost.findBlogPost(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BlogPost' with identifier '" + id + "'", BlogPost.findBlogPost(id));
    }
    
}
